name: Send submodule updates to parent repo

on:
  push:
    branches:
      - main

jobs:
  updating-to-parent-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Pottani-Space/pottaniweb
          token: ${{ secrets.TOKEN }}
          submodules: true
      
      - name: Pull & Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      
      - name: Stage Submodule Changes
        run: |
          # Stage any changes to the submodule itself
          git add .gitmodules
          # Stage changes within each submodule
          git add $(git submodule --quiet foreach 'echo $sm_path')
      
      - name: Check for Changes
        id: check_changes
        run: |
          git diff --cached --exit-code || echo "changes"

      - name: Commit and Push
        if: steps.check_changes.outputs.changes == 'changes'
        run: |
          git config user.email "actions@github.com"
          git config user.name "Github Actions - Update"
          git commit -m "feat: Update submodules"
          git push
      
      - name: Debug Final Status
        run: |
          echo "Final repository status:"
          git status
