name: Send repository dispatch event

on:
  push:
    branches:
      - main

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:
      - name: Fire event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Pottani-Space/pottaniweb/dispatches \
            -d '{"event_type":"dispatch-event"}'
